#!/usr/bin/env bash

SRCDIR="$HOME/src"

if hash xbps-install 2>/dev/null; then
    SYSTEM_UPDATE="sudo xbps-install -Suv"
elif hash eopkg 2>/dev/null; then
    SYSTEM_UPDATE="sudo eopkg up"
else
    echo "Your system is not supported, you will have to set SYSTEM_UPDATE manually"
fi


#build source files
build_source() {
    echo "Configuring"
    if [ -e configure ]; then
       ./configure --prefix=/usr
    fi
    echo "Building"
    if [ -e Makefile ]; then
        make > /dev/null
    fi
    if [ -e install.sh ]; then
        ./install.sh
    fi
    if [ -e Cargo.toml ]; then
        cargo build --release
    fi
}
#install the source build
install_build() {
    build_source
    if [ -e Makefile ]; then
        sudo make install > /dev/null
    fi
}

fetch_repo() {
    if [ -d ".git" ]; then #check if its a git repo and pull if it is
        printf "Updating %s : " "$(basename `pwd`)"
        if [[ $(git pull) =~ "Already up-to-date" ]]; then
            echo "$(basename `pwd`) done."
        fi
    fi
}

#do system updates
update_system() {
    if [ -z "$SYSTEM_UPDATE" ]; then
        echo "SYSTEM_UPDATE not set"
    else
        $SYSTEM_UPDATE
    fi

}

update_system&
for repo in $SRCDIR/* ; do
    cd $repo
    fetch_repo&
done
wait
for repo in $SRCDIR/* ; do
    cd $repo
    install_build&
wait
